### ISSUE TITLE
need at least one array to concatenate

### ISSUE THREAD

**Issue by Joaovsky** [VisualComputingInstitute/vkitti3D-dataset#7]
I'm following this codebase so I can get virtual lidar point cloud data to train a MVXNET model with both real and virtual kitti dataset.

When I do the following command:

python create_npy.py --root_path /home/mola/data/vkitti3D-dataset/datasets --out_path /home/mola/data/vkitti3D-dataset/datasets/vkitti_npy --sequence 0001 --v2

I get this error on debug: AttributeError: 'DataFrame' object has no attribute '_mgr'

And my full log before spotting the error is:

Program was launched with the following arguments:
~ root_path      /home/mola/data/vkitti3D-dataset/datasets
~ out_path       /home/mola/data/vkitti3D-dataset/datasets/vkitti_npy
~ bb_eps         0.3
~ cutoff         100.0
~ knn_eps        0.2
~ knn_number     1
~ sequence       0001
~ njobs          4
~ is_v1          False

Processing sequence 0001 ...

0.00it [00:00, ?it/s]
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "create_npy.py", line 462, in <module>
    main(args.root_path, args.out_path, args.bb_eps, args.cutoff, args.knn_eps,
  File "create_npy.py", line 364, in main
    overall_scene = np.vstack([output[i][0] for i in range(len(output))])
  File "<__array_function__ internals>", line 180, in vstack
  File "/home/mola/miniconda3/envs/openmmlab/lib/python3.8/site-packages/numpy/core/shape_base.py", line 282, in vstack
    return _nx.concatenate(arrs, 0)
  File "<__array_function__ internals>", line 180, in concatenate
ValueError: need at least one array to concatenate

Can anyone tell me what I'm doing wrong?

**Comment by Joaovsky** [comment]
Resolved. I must have done some change in the datasets so I remove them and downloaded again.
